### ISSUE TITLE
Trailsmix

### ISSUE THREAD

**Issue by nogtini** [trailsjs/trailsmix#1]
Working on a React app/"environment component" called TrailsMix which allows the user to configure his/her build and generate a Trails app with the respective trails-packs installed via a single command line.

This will help others immediately grasp the modularity of the new Trails ecosystem and get them set up effortlessly.

Will extend itself into all domains of a full-stack build -> backend serving, routing, devops, bundler, front-end templating, ORM, etc.

Graphic only shows beginnings of build, bundling, middleware, and auth.

![trailsmix](https://cloud.githubusercontent.com/assets/5909827/11754543/0405cb02-a01a-11e5-9606-b233b9571b4d.png)

**Comment by tjwebb** [comment]
I still like "trailmix" better. Maybe it's trademarked.

**Comment by nogtini** [comment]
How about TrailsMix camel-cased for clarity?

It's supposed to be a pun of the word trailmix using the name of the framework and the idea that you're "mixing Trails".

Also useful for SEO and discussion in general.

**Comment by DaAwesomeP** [comment]
You can select Bower at the same time as Grunt or Gulp, right? I can't imagine why you wouldn't want to.

Also, you'll be competing with a lot (and will have a lot to maintain) if you implement front-end generation. Take [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular), for example. It has a crazy amount of options for what it is. However, I use it for nearly all of my apps now. I can choose _Angular 1.4+all major Angular components+Bootstrap+UI Bootstrap+SASS+ES6+Image compression_. That's a lot of selection to implement on your end, and then you'll have to repeat it for React, Ember, etc.

**Comment by nogtini** [comment]
As a core Trails application will consist of multiple Trailpacks, TrailsMix is simply an interface which will facilitate the generation and bundling.

You raise a good point about the desire to select multiple build tools; I was originally thinking of enabling the user to choose only one per category, but I think simply categorizing them and letting the user select as many as they desire a la carte is the way to go.
