### ISSUE TITLE
Trails allow only one web server 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailsmix#7]
For now TrailsMix allow to choose multiple web server, but Trails only allow one. I know this only the beginning but put it here to don't forget later :)

**Comment by nogtini** [comment]
This is a good opportunity to add a little bit of guidance in the build/configuration process. I'll come up with a logical "walk-through" that can be added above the card rows, with the information panel adding supplementary information.

It should also be worth asking ourselves, is there _ever_ a time when a combination of Hapi/Express/Koa need to be installed? If the answer is yes, we should leave it as is.

**Comment by nogtini** [comment]
Closed by bfe00e4c30cdd8cdd7d3139ce8f52b3b33fafbfd
